#!/usr/bin/env bash

set -euo pipefail

get-refspecs() {
        INPUT_REMOTE="${1}"
        git branch --list --format "%(refname:short):%(upstream:remotename):%(upstream:lstrip=3)" \
        | while IFS=":" read -r LOCAL REMOTE REMOTEREF
        do
                if [ "${REMOTE}" != "${INPUT_REMOTE}" ]; then
                        continue
                fi
                if [ -z "${REMOTEREF}" ]; then
                        continue
                fi
                if ! git show-ref --verify --quiet "refs/remotes/${REMOTE}/${REMOTEREF}"; then
                        continue
                fi
                echo "${LOCAL}:${REMOTEREF}"
        done
}

for REMOTE in $(git remote); do
        git remote prune "${REMOTE}"
        get-refspecs "${REMOTE}" | xargs --verbose git fetch "${REMOTE}" --update-head-ok
done