#!/usr/bin/env bash

## git-fixup: fixup and rebase interactively.
## requires fzf

set -euo pipefail

get-base() {
        local REMOTE_HEAD;
        local REMOTE_BASE;
        local REFNAME;
        local UPSTREAM;
        for REMOTE_HEAD in $(git for-each-ref --format '%(refname)' 'refs/remotes/*/HEAD'); do
                REMOTE_BASE=$(git symbolic-ref "$REMOTE_HEAD")
                while read -r REFNAME UPSTREAM; do
                        if [ "$UPSTREAM" == "$REMOTE_BASE" ]; then
                                echo "$REFNAME"
                                return
                        fi
                done < <(git branch --list --format '%(refname) %(upstream)')
        done
        >&2 echo "Cannot detect a branch that tracks the remote HEAD branch. Try following commands:"
        >&2 echo "  git switch <base branch>"
        >&2 echo "  git remote set-head --auto <remote name>"
        >&2 echo "  git branch --set-upstream-to <remote name>/<base branch>"
        >&2 echo "Or give git-fixup a base branch explicitly: git fixup <base branch>"
        return 1
}

BASE=${1:-}
if [ -z "$BASE" ]; then
        BASE=$(get-base)
fi
BASE=$(git rev-parse "$BASE")

if git diff --cached --quiet; then
        git rebase -i --autosquash --autostash --onto "$BASE"... "$BASE"
        exit
fi

CURRENT=$(git branch --show-current)
if [ -z "${CURRENT}" ]; then
        echo "Detached head"
        exit -1
fi

MERGE_BASE=$(git merge-base "${BASE}" HEAD)
COMMITS=$(git log --oneline "$MERGE_BASE"..HEAD)
if [ -z "${COMMITS}" ]; then
        COMMITS=$(git log --oneline HEAD~1..HEAD)
fi
select-commit() {
        fzf --preview 'git show --color=always {1}' --preview-window up:80% \
        | awk '{ print $1 }'
}
FIXUP=$(echo "${COMMITS}" | select-commit "${COMMITS}")

git commit --fixup "${FIXUP}"
git rebase -i --autosquash --autostash --onto "$BASE"... "$BASE"