#!/usr/bin/env bash

## git-fixup: fixup and rebase interactively.
## requires fzf

set -euo pipefail

BASE=${1:-master}

if git diff --cached --quiet; then
        echo "Empty index"
        exit -1
fi

CURRENT=$(git branch --show-current)
if [ -z "${CURRENT}" ]; then
        echo "Detached head"
        exit -1
fi

MERGE_BASE=$(git merge-base "${BASE}" HEAD)
COMMITS=$(git log --oneline "$MERGE_BASE"..HEAD)
if [ -z "${COMMITS}" ]; then
        COMMITS=$(git log --oneline HEAD~1..HEAD)
fi
select-commit() {
        fzf --preview 'git show --color=always {1}' --preview-window up:80% \
        | awk '{ print $1 }'
}
FIXUP=$(echo "${COMMITS}" | select-commit "${COMMITS}")

git commit --fixup "${FIXUP}"
git rebase -i --autosquash --autostash --onto "$BASE"... "$BASE"