#!/usr/bin/env bash

# git-sync: pull, prune, trim all branches.
# requires: git-trim

set -euo pipefail

CURRENT=$(git branch --show-current)

get-refspecs() {
        INPUT_REMOTE="${1}"
        git branch --list --format "%(refname:short):%(upstream:remotename):%(upstream:lstrip=3)" \
        | while IFS=":" read -r LOCAL REMOTE REMOTEREF
        do
                if [ "${LOCAL}" == "${CURRENT}" ]; then
                        continue
                fi
                if [ "${REMOTE}" != "${INPUT_REMOTE}" ]; then
                        continue
                fi
                if [ -z "${REMOTEREF}" ]; then
                        continue
                fi
                if ! git show-ref --verify --quiet "refs/remotes/${INPUT_REMOTE}/${REMOTEREF}"; then
                        continue
                fi
                echo "${LOCAL}:${REMOTEREF}"
        done
}

for REMOTE in $(git remote); do
        get-refspecs "${REMOTE}" | xargs --verbose git fetch --prune "${REMOTE}" $(git config "remote.${REMOTE}.fetch")
done

if [ -n "${CURRENT}" ]; then
        UPSTREAM=$(git branch --list --format "%(upstream)" "${CURRENT}")
        git merge --ff-only "${UPSTREAM}"
fi

git trim --no-update